use_frameworks!
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'QWListKit_Example' do
  pod 'QWListKit', :path => '../'

  target 'QWListKit_Tests' do
    inherit! :search_paths
  end
end
