use_frameworks!
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'QWListKit_Example' do
  pod 'QWListKit', :path => '../'
  
  pod 'Then'

  target 'QWListKit_Tests' do
    inherit! :search_paths
  end
end
